## Import NumPy

In [2]:
import numpy as np

## Create NumPy arrays

### Create following 1d arrays

```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

array([1., 1., 1., 1., 1.])

```


In [ ]:
arr_1 = np.arange(1,101,dtype=int)
arr_1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr_2 = np.zeros(5)
arr_2

array([0., 0., 0., 0., 0.])

### Create following 2d arrays

```
array([[31, 22, 48],
       [52, 33, 40],
       [72,  8, 37]])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

```

In [ ]:
arr_3 = np.random.randint(8,52,9)
arr_3
np.reshape(arr_3,(3,3))

array([[11, 44, 20],
       [35, 17, 14],
       [51, 44, 42]])

In [ ]:
np.zeros(20).reshape(4,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.arange(0,24).reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Generate arrays with random numbers

- 1d array with 10 numbers from random uniform distribution
- 1d array with 25 numbers from normal distribution
- 4 x 5 array from random integer in [0, 100]

In [ ]:
unif = np.random.rand(10)
unif

array([0.99471644, 0.58657874, 0.05702379, 0.35985593, 0.6565951 ,
       0.50863838, 0.83508022, 0.40923441, 0.68333472, 0.60786048])

In [ ]:
nd = np.random.randn(25)
nd

array([-1.91640115, -0.38719739, -0.08679969,  0.02689609, -0.5258109 ,
        1.78834857,  2.65787992,  2.25154085, -1.1278204 , -2.48050057,
        0.62863857, -0.67074602, -0.89405586,  1.02864853, -0.04105639,
       -0.29604776, -0.21475604,  0.29723058,  1.53125674, -0.62252134,
        1.04812634, -0.46758593,  1.29252113, -1.27707191,  1.45679057])

In [ ]:
np.random.randint(0,100,20).reshape(4,5)

array([[65, 31, 23, 27, 13],
       [13, 45, 52, 32, 43],
       [56, 92, 60, 79, 79],
       [94, 37, 45, 94, 99]])

## Array Indexing



### 1d array indexing 

- From the following array, extract the elements shown below 

In [ ]:
arr_1d = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 
                   53, 54, 55, 56, 57, 58, 59, 60])

1. 
    ```
    array([41, 42, 43, 44])
    ```
1. 
    ```
    array([56, 57, 58, 59, 60])
    ```
1. 
    ```
    array([51, 52, 53])
    ```
1. 
    ```
    array([42, 55, 49])
    ```


In [ ]:
arr_1d[0:5]

array([41, 42, 43, 44, 45])

In [ ]:
arr_1d[-5:]

array([56, 57, 58, 59, 60])

In [ ]:
arr_1d[10:13]

array([51, 52, 53])

In [ ]:
arr_1d[[1,15,9]]

array([42, 56, 50])

### 2d array indexing

- Do the same task for the following 2d array


In [ ]:
arr_2d = np.array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

Using indexing, generate the following sub-arrays

1. 
    ```
    array([[31, 32, 33, 34, 35],
          [41, 42, 43, 44, 45]])
    ```
1. 
    ```
    array([[11, 12],
          [21, 22],
          [31, 32],
          [41, 42]])    
    ```
1. 
    ```
    array([[32, 33],
           [42, 43]])
    ```
1. 
    ```
    array([[23, 25],
          [43, 45]])    
    ```


In [ ]:
arr_2d[2:4]

array([[31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [ ]:
arr_2d[0:4,0:2]

array([[11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [ ]:
arr_2d[2:4,1:3]

array([[32, 33],
       [42, 43]])

In [ ]:
arr_2d[[1,3]][:,[2,4]]

array([[23, 25],
       [43, 45]])

In [ ]:
arr_int = np.array([-448,  754,  990,   18, -689,  641, -199,  -44, -557, -222,  -18,
       -687,  -69,  106,  821,  628, -427, -269, -624, -478,  886,  841,
        999,   99,  964, -312,   42,  186,  298,  170, -441,  761,  900,
       -207,  626, -322, -351,  169,  523, -131, -508,  181,  714,  171,
       -131,  525,  810, -173,  424, -265,  242,  313,   57,  423,  685,
        -16,  732,  372,  661,  654, -106,  443,  281, -125,  523,  476,
        525,  577,  938, -140,  333,  180, -348,  591, -135,  961,  805,
       -488, -422,  538, -433,  873,  568, -202, -181,  986,  769, -682,
       -645,  883, -529,  -27,  656,  153, -165, -242, -678,  635, -135,
        364])

For the array above, find the following numbers
 - The max/min number
 - Standard deviation of the array
 - Mean 


## Array Operations (2d)


In [ ]:
arr_normal = np.array([[-1.35589711,  0.32804138, -0.42081221, -0.26130734,  0.70162537,
        -2.74984249,  0.68124585, -0.1580792 , -0.14275744,  0.46342884,
         0.86430316, -0.07669887],
       [-0.74704059, -0.9071367 , -1.64174011,  0.03933122,  0.37675907,
         1.90269555,  0.44306442,  0.57069955, -0.28930021, -1.65834518,
         0.91165489, -0.24778658],
       [ 0.84422231, -2.61441156, -0.25364573,  0.75980507,  0.81245918,
         0.4495238 , -1.73419967,  0.06119128,  0.20092236, -0.02241897,
        -0.35468241, -1.10875505],
       [-1.2590743 , -1.798422  ,  0.29824561,  0.61399003, -2.84641582,
        -0.06309182, -0.86245245, -2.00527547, -1.36537977,  1.81020212,
         0.15409758,  0.77957902],
       [ 0.33642384,  1.6658424 ,  1.01517418, -0.94632536, -0.67836296,
        -1.58780134, -1.71699404,  0.19439649,  0.16351275, -2.08961948,
        -0.67480237, -0.98241524],
       [-0.97960876,  0.7256977 ,  0.2322489 , -0.79256359, -0.86636526,
         1.01071361,  0.06147106,  0.31257068,  0.54583426, -0.8035504 ,
         0.73390521,  0.05112845],
       [-0.17791452, -0.92611399,  0.27351997,  0.25378587,  0.78804843,
        -1.06393523,  2.65299826, -0.91232348, -2.93197926,  1.73152395,
         0.59431283, -0.10374418],
       [ 0.57609783,  0.51063139, -0.06848566,  2.65524085,  0.90236844,
        -0.63241958,  0.99904813, -0.6191799 ,  0.44955157, -1.99264591,
        -0.94398059, -0.68643509],
       [ 0.0329195 , -0.64513047,  0.46339352,  0.22950196,  1.03883248,
         2.09548912,  0.91148567, -1.05809727, -2.82315242, -1.24258192,
         0.32577142, -0.56579935],
       [ 0.76420142,  0.4468688 ,  0.69440669, -0.69501969,  0.99550496,
         0.04774205, -0.38475403, -0.34571432, -1.54386284,  2.93070093,
         0.55347872, -0.90081639]])

In [ ]:
arr_normal.shape

(10, 12)

For the array above, find the following numbers
 - The max/min number 
    - in the entire array
    - in each row
    - in each column
 - Mean of 
    - the entire array
    - each row 
    - each column


In [ ]:
print("Mean:",np.mean(arr_normal))
print("Max:",np.max(arr_normal))
print("Min:",np.min(arr_normal))

Mean: -0.1274502665833333
Max: 2.93070093
Min: -2.93197926


In [ ]:
for i in range(10):
  j = i + 1
  print("Row",j,"- Mean:",np.mean(arr_normal[i:j]))
  print("Row",j,"- Max:",np.max(arr_normal[i:j]))
  print("Row",j,"- Min:",np.mean(arr_normal[i:j]))

Row 1 - Mean: -0.17722917166666666
Row 1 - Max: 0.86430316
Row 1 - Min: -0.17722917166666666
Row 2 - Mean: -0.10392872249999997
Row 2 - Max: 1.90269555
Row 2 - Min: -0.10392872249999997
Row 3 - Mean: -0.2466657825
Row 3 - Max: 0.84422231
Row 3 - Min: -0.2466657825
Row 4 - Mean: -0.5453331058333334
Row 4 - Max: 1.81020212
Row 4 - Min: -0.5453331058333334
Row 5 - Mean: -0.4417475941666667
Row 5 - Max: 1.6658424
Row 5 - Min: -0.4417475941666667
Row 6 - Mean: 0.019290155000000003
Row 6 - Max: 1.01071361
Row 6 - Min: 0.019290155000000003
Row 7 - Mean: 0.014848220833333337
Row 7 - Max: 2.65299826
Row 7 - Min: 0.014848220833333337
Row 8 - Mean: 0.09581595666666665
Row 8 - Max: 2.65524085
Row 8 - Min: 0.09581595666666665
Row 9 - Mean: -0.10311398
Row 9 - Max: 2.09548912
Row 9 - Min: -0.10311398
Row 10 - Mean: 0.21356135833333334
Row 10 - Max: 2.93070093
Row 10 - Min: 0.21356135833333334


In [ ]:
for i in range(12):
  j = i + 1
  print("column",j,"- Mean:",np.mean(arr_normal[0:11,i:j]))
  print("column",j,"- Max:",np.max(arr_normal[0:11,i:j]))
  print("column",j,"- Min:",np.min(arr_normal[0:11,i:j]))

column 1 - Mean: -0.19656703799999997
column 1 - Max: 0.84422231
column 1 - Min: -1.35589711
column 2 - Mean: -0.3214133049999999
column 2 - Max: 1.6658424
column 2 - Min: -2.61441156
column 3 - Mean: 0.059230516
column 3 - Max: 1.01517418
column 3 - Min: -1.64174011
column 4 - Mean: 0.18564390199999997
column 4 - Max: 2.65524085
column 4 - Min: -0.94632536
column 5 - Mean: 0.12244538899999999
column 5 - Max: 1.03883248
column 5 - Min: -2.84641582
column 6 - Mean: -0.05909263299999995
column 6 - Max: 2.09548912
column 6 - Min: -2.74984249
column 7 - Mean: 0.10509131999999996
column 7 - Max: 2.65299826
column 7 - Min: -1.73419967
column 8 - Mean: -0.395981164
column 8 - Max: 0.57069955
column 8 - Min: -2.00527547
column 9 - Mean: -0.7736610999999999
column 9 - Max: 0.54583426
column 9 - Min: -2.93197926
column 10 - Mean: -0.08733060200000006
column 10 - Max: 2.93070093
column 10 - Min: -2.08961948
column 11 - Mean: 0.21640584399999999
column 11 - Max: 0.91165489
column 11 - Min: -0.9439

# Control Sequences (optional)

## Programming FizzBuzz

Write a code for FizzBuzz. The definition of the program is:

> A program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”. (from [here](https://www.tomdalling.com/blog/software-design/fizzbuzz-in-too-much-detail/#:~:text=FizzBuzz%20is%20a%20very%20simple,numbers%20from%201%20to%20100))

##### Note:

- You can find numerous examples online, but please try by yourself :)
- The output is like:
    ```
    [1, 2, 'Fizz', 4, 'Buzz', 'Fizz', 7, 8, 'Fizz', 'Buzz', 11, 'Fizz', 13, 14,
     'FizzBuzz', 16, 17, 'Fizz', 19, 'Buzz', 'Fizz', 22, 23, 'Fizz', 'Buzz', 
     26, 'Fizz', 28, 29, 'FizzBuzz', 31, 32, 'Fizz', 34, 'Buzz', 'Fizz', 37, 
     38, 'Fizz', 'Buzz', 41, 'Fizz', 43, 44, 'FizzBuzz', 46, 47, 'Fizz', 49, 
     'Buzz', 'Fizz', 52, 53, 'Fizz', 'Buzz', 56, 'Fizz', 58, 59, 'FizzBuzz', 
     61, 62, 'Fizz', 64, 'Buzz', 'Fizz', 67, 68, 'Fizz', 'Buzz', 71, 'Fizz', 
     73, 74, 'FizzBuzz', 76, 77, 'Fizz', 79, 'Buzz', 'Fizz', 82, 83, 'Fizz', 
     'Buzz', 86, 'Fizz', 88, 89, 'FizzBuzz', 91, 92, 'Fizz', 94, 'Buzz', 
     'Fizz', 97, 98, 'Fizz']
    ```
- You need to know how to use `%` (Modulus) operator ([Link](https://www.tutorialspoint.com/python/python_basic_operators.htm))



In [10]:
nset = np.arange(1,100)
newset = []
for p in nset:
  if p % 15 == 0:
    newset.append("FizzBuzz")
  elif p % 3 == 0:
    newset.append("Fizz")
  elif p % 5 == 0:
    newset.append("Buzz")
  else:
    newset.append(p)
print(np.reshape(newset,(9,11)))

[['1' '2' 'Fizz' '4' 'Buzz' 'Fizz' '7' '8' 'Fizz' 'Buzz' '11']
 ['Fizz' '13' '14' 'FizzBuzz' '16' '17' 'Fizz' '19' 'Buzz' 'Fizz' '22']
 ['23' 'Fizz' 'Buzz' '26' 'Fizz' '28' '29' 'FizzBuzz' '31' '32' 'Fizz']
 ['34' 'Buzz' 'Fizz' '37' '38' 'Fizz' 'Buzz' '41' 'Fizz' '43' '44']
 ['FizzBuzz' '46' '47' 'Fizz' '49' 'Buzz' 'Fizz' '52' '53' 'Fizz' 'Buzz']
 ['56' 'Fizz' '58' '59' 'FizzBuzz' '61' '62' 'Fizz' '64' 'Buzz' 'Fizz']
 ['67' '68' 'Fizz' 'Buzz' '71' 'Fizz' '73' '74' 'FizzBuzz' '76' '77']
 ['Fizz' '79' 'Buzz' 'Fizz' '82' '83' 'Fizz' 'Buzz' '86' 'Fizz' '88']
 ['89' 'FizzBuzz' '91' '92' 'Fizz' '94' 'Buzz' 'Fizz' '97' '98' 'Fizz']]
